'use client';
import { useEffect,useMemo,useState } from 'react';

type Slot={startTime:string;endTime:string;booked:boolean};
const rate=Number(process.env.NEXT_PUBLIC_HOURLY_RATE||500);
export default function BookingWidget(){
 const today=new Date().toISOString().slice(0,10); const [date,setDate]=useState(today); const [slots,setSlots]=useState<Slot[]>([]); const [selected,setSelected]=useState<Slot|null>(null); const [loading,setLoading]=useState(false); const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);
 const [form,setForm]=useState({customerName:'',email:'',phone:'',players:'2',notes:''});
 useEffect(()=>{setSelected(null);fetch(`/api/bookings?date=${date}`).then(r=>r.json()).then(d=>setSlots(d.slots||[]));},[date]);
 const update=(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm({...form,[e.target.name]:e.target.value});
 async function submit(e:React.FormEvent){e.preventDefault();setMessage(null);if(!selected){setMessage({ok:false,text:'Please select an available time slot.'});return}setLoading(true);const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,date,startTime:selected.startTime})});const d=await r.json();setLoading(false);if(!r.ok){setMessage({ok:false,text:d.error||'Booking failed.'});return}setMessage({ok:true,text:`Booking confirmed! Reference: ${d.booking.reference}`});setForm({customerName:'',email:'',phone:'',players:'2',notes:''});setSelected(null);fetch(`/api/bookings?date=${date}`).then(r=>r.json()).then(d=>setSlots(d.slots||[]));}
 const selectedLabel=useMemo(()=>selected?`${selected.startTime} – ${selected.endTime}`:'Choose a time', [selected]);
 return <div className="booking-shell"><div className="booking-grid"><div><div className="calendar-title">Choose your date & time</div><div className="field"><label>Date</label><input type="date" min={today} value={date} onChange={e=>setDate(e.target.value)}/></div><div className="small" style={{margin:'10px 0 12px'}}>₱{rate.toLocaleString()} / hour · 1 court · 6:00 AM–10:00 PM</div><div className="slots">{slots.map(s=><button type="button" key={s.startTime} disabled={s.booked} className={`slot ${s.booked?'booked':''} ${selected?.startTime===s.startTime?'selected':''}`} onClick={()=>setSelected(s)}>{s.startTime}<br/><span className="small">{s.booked?'Booked':`₱${rate}`}</span></button>)}</div></div><form onSubmit={submit}><div className="calendar-title">Your booking details</div>{message&&<div className={`notice ${message.ok?'success':'error'}`}>{message.text}</div>}<div className="field"><label>Full name</label><input required name="customerName" value={form.customerName} onChange={update} placeholder="Juan Dela Cruz"/></div><div className="field"><label>Email</label><input required type="email" name="email" value={form.email} onChange={update} placeholder="juan@email.com"/></div><div className="field"><label>Mobile number</label><input required name="phone" value={form.phone} onChange={update} placeholder="09XXXXXXXXX"/></div><div className="field"><label>Number of players</label><select name="players" value={form.players} onChange={update}>{[2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></div><div className="field"><label>Notes (optional)</label><textarea rows={3} name="notes" value={form.notes} onChange={update} placeholder="Any special request?"/></div><div className="summary"><div className="summary-row"><span>Selected slot</span><strong>{selectedLabel}</strong></div><div className="summary-row"><span>Total</span><strong>₱{rate.toLocaleString()}</strong></div></div><button className="btn btn-primary" style={{width:'100%'}} disabled={loading}>{loading?'Booking...':'Reserve Court'}</button><p className="small center">You can connect GCash/Maya/PayMongo later. This starter keeps payment status ready in the database.</p></form></div></div>
}
